---
grav_container_name: grav
grav_image: "ghcr.io/sepp67/grav-nginx:latest"
grav_http_port: 18090

grav_base_dir: /opt/grav
grav_data_dir: "{{ grav_base_dir }}/data"

grav_restart_policy: unless-stopped
